version: '3.6'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8008
    volumes:
     - .:/code
    ports:
      - 8008:8008
    env_file:
      - ./.env.dev
    depends_on:
      - db

volumes:
  postgres_data:
