version: '3'

services:
  db:
    image: postgres:10
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /opt/pg-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db
